### ISSUE TITLE
The lib of libwebview.so only supports gtk3, and Lazarus LCL only supports gtk2, so the demo of lclembed is failed to run

### ISSUE THREAD

**Issue by guijunchao** [PierceNg/fpwebview#10]
Env: UOS 20.9(linux) + Lazarus 2.2.6

Build the demo of lclembed with IDE, run it with linrun.sh, error msg:
(lclembed:413784): Gtk-ERROR **: 11:59:08.552: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported
Trace/breakpoint trap

linrun.sh script:
#!/bin/sh
LD_LIBRARY_PATH=`pwd` ./lclembed

If build the demo with linbuild.sh, error msg:

Free Pascal Compiler version 3.2.2 [2021/07/09] for x86_64
Copyright (c) 1993-2021 by Florian Klaempfl and others
Target OS: Linux for x86-64
Compiling lclembed.lpr
(LCLEMBED) Registering new unit SYSTEM
(LCLEMBED) Load from LCLEMBED (implementation) unit SYSTEM
(SYSTEM)   Loading unit SYSTEM
(SYSTEM)   PPU Name: /usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/system.ppu
(SYSTEM)   PPU Time: 2021/07/09 11:43:06
(SYSTEM)   PPU Flags: 159873
(SYSTEM)   PPU Crc: C9D9E0D9
(SYSTEM)   PPU Crc: 531A4B0E (intfc)
(SYSTEM)   PPU Crc: 4EF193DD (indc)
(SYSTEM)   Number of definitions: 2651
(SYSTEM)   Number of symbols: 8182
(SYSTEM)   PPU Source: system.pp not available
(SYSTEM)   PPU Source: osdefs.inc not available
(SYSTEM)   PPU Source: sysunixh.inc not available
(SYSTEM)   PPU Source: systemh.inc not available
....
(UNIXUTIL) Loading unit UNIXUTIL
(UNIXUTIL) PPU Name: /usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/unixutil.ppu
(UNIXUTIL) PPU Time: 2021/07/09 11:43:06
(UNIXUTIL) PPU Flags: 143488
(UNIXUTIL) PPU Crc: A5FC410E
(UNIXUTIL) PPU Crc: 6AB6AC1B (intfc)
(UNIXUTIL) PPU Crc: 4EF193DD (indc)
(UNIXUTIL) Number of definitions: 9
(UNIXUTIL) Number of symbols: 50
(UNIXUTIL) PPU Source: unixutil.pp not available
(UNIXUTIL) Load from UNIXUTIL (interface) unit SYSTEM
(UNIXUTIL) Adding dependency: UNIXUTIL depends on SYSTEM
(UNIXUTIL) Finished loading unit UNIXUTIL
(UNIX)     Adding dependency: UNIX depends on UNIXUTIL
(UNIX)     Load from UNIX (implementation) unit SYSCALL
(UNIX)     Adding dependency: UNIX depends on SYSCALL
(UNIX)     Finished loading unit UNIX
(CTHREADS) Adding dependency: CTHREADS depends on UNIX
(CTHREADS) Load from CTHREADS (implementation) unit UNIXTYPE
(CTHREADS) Adding dependency: CTHREADS depends on UNIXTYPE
(CTHREADS) Load from CTHREADS (implementation) unit INITC
(INITC)    Loading unit INITC
(INITC)    PPU Name: /usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/initc.ppu
(INITC)    PPU Time: 2021/07/09 11:43:06
(INITC)    PPU Flags: 143488
(INITC)    PPU Crc: FC1AE8F5
(INITC)    PPU Crc: 020CC9B5 (intfc)
(INITC)    PPU Crc: 4EF193DD (indc)
(INITC)    Number of definitions: 6
(INITC)    Number of symbols: 10
(INITC)    PPU Source: initc.pp not available
(INITC)    Registering new unit CTYPES
(INITC)    Load from INITC (interface) unit SYSTEM
(INITC)    Adding dependency: INITC depends on SYSTEM
(INITC)    Load from INITC (interface) unit CTYPES
(CTYPES)   Loading unit CTYPES
(CTYPES)   PPU Name: /usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/ctypes.ppu
(CTYPES)   PPU Time: 2021/07/09 11:43:06
(CTYPES)   PPU Flags: 143488
(CTYPES)   PPU Crc: 0D029B26
(CTYPES)   PPU Crc: B1FE86DC (intfc)
(CTYPES)   PPU Crc: 00000000 (indc)
(CTYPES)   Number of definitions: 2
(CTYPES)   Number of symbols: 65
(CTYPES)   PPU Source: ctypes.pp not available
(CTYPES)   PPU Source: aliasctp.inc not available
(CTYPES)   Load from CTYPES (interface) unit SYSTEM
(CTYPES)   Adding dependency: CTYPES depends on SYSTEM
(CTYPES)   Load from CTYPES (interface) unit UNIXTYPE
(CTYPES)   Adding dependency: CTYPES depends on UNIXTYPE
(CTYPES)   Finished loading unit CTYPES
(INITC)    Adding dependency: INITC depends on CTYPES
(INITC)    Finished loading unit INITC
(CTHREADS) Adding dependency: CTHREADS depends on INITC
(CTHREADS) Load from CTHREADS (implementation) unit DL
(DL)       Loading unit DL
(DL)       PPU Name: /usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/dl.ppu
(DL)       PPU Time: 2021/07/09 11:43:06
(DL)       PPU Flags: 143489
(DL)       PPU Crc: 5DFC9E82
(DL)       PPU Crc: FFD8DEA1 (intfc)
(DL)       PPU Crc: 4EF193DD (indc)
(DL)       Number of definitions: 27
(DL)       Number of symbols: 56
(DL)       PPU Source: dl.pp not available
(DL)       Load from DL (interface) unit SYSTEM
(DL)       Adding dependency: DL depends on SYSTEM
(DL)       Load from DL (implementation) unit CTYPES
(DL)       Adding dependency: DL depends on CTYPES
(DL)       Finished loading unit DL
(CTHREADS) Adding dependency: CTHREADS depends on DL
(CTHREADS) Finished loading unit CTHREADS
(LCLEMBED) Load from LCLEMBED (implementation) unit INTERFACES
(INTERFACES) Loading unit INTERFACES
lclembed.lpr(9,3) Fatal: Can't find unit Interfaces used by lclembed
Fatal: Compilation aborted
Error: /usr/bin/ppcx64 returned an error exitcode

**Comment by PierceNg** [comment]
This is limitation of GTK, as seen in the error message:

> (lclembed:413784): Gtk-ERROR **: 11:59:08.552: GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported

I've stated this limitation explicitly in the [demo's README](https://github.com/PierceNg/fpwebview/tree/feb2023/demo/lclembed) of the current WIP branch:

> The demo works on macOS (using Lazarus Cocoa widget set) and Windows (using Lazarus Windows widget set).
>
> For Linux:
>
> - with Lazarus GTK2: Impossible, as GTK2 and GTK3 (which webview on Linux uses) cannot run as one executable.
>
> - with Lazarus GTK3: Should be trivial. Note that at present Lazarus GTK3 is work-in-progress and not mature.
>
> - with Lazarus Qt5/Qt6: Possible, potentially tricky. The basic requirement is to convert a Qt window handle into a GTK3 window suitable for use with webview.

**Comment by guijunchao** [comment]
OK，thanks a lot!
