### ISSUE TITLE
Error compiling demos in windows.

### ISSUE THREAD

**Issue by ucuccen** [PierceNg/fpwebview#11]
Hello, 
trying to compile the first demos but not succed.
here is the result :
`
    C:\tmp\fpwebview\demo\browser_cli>winbuild.bat
    Set up FPC executable path.
    "C:\GNU\fpc323\App\fpc\bin\i386-win32\fpc.exe"
    Building...
            1 file(s) copied.
            1 file(s) copied.
            1 file(s) copied.
    Free Pascal Compiler version 3.2.3-1334-ga6764eccd9 [2024/01/09] for i386
    Copyright (c) 1993-2021 by Florian Klaempfl and others
    Target OS: Win32 for i386
    Compiling browser_cli.lpr
    Compiling C:\tmp\fpwebview\src\webview.pas
    Linking browser_cli.exe
    browser_cli.lpr(25,1) Error: Illegal COFF Magic while reading libwebview.a(impwebview1s2.o)
    browser_cli.lpr(25,1) Error: Illegal COFF Magic while reading libwebview.a(impwebview1s9.o)
    browser_cli.lpr(25,1) Error: Illegal COFF Magic while reading libwebview.a(impwebview1s8.o)
    browser_cli.lpr(25,1) Error: Illegal COFF Magic while reading libwebview.a(impwebview1s10.o)
    browser_cli.lpr(25,1) Error: Illegal COFF Magic while reading libwebview.a(impwebview1s4.o)
    browser_cli.lpr(25,1) Error: Illegal COFF Magic while reading libwebview.a(impwebview1s3.o)
    browser_cli.lpr(25,1) Fatal: There were 6 errors compiling module, stopping
    Fatal: Compilation aborted
    Error: C:\GNU\fpc323\App\fpc\bin\i386-win32\ppc386.exe returned an error exitcode
     
`

and here is the winbuild.bat
`
@echo off
 
echo Set up FPC executable path.
set pfpc=C:\GNU\fpc323\App\fpc\bin\i386-win32
set path=%path%
 
set fpcexe=%pfpc%\fpc.exe
 
if not exist "%fpcexe%" (
        echo ERROR: Edit this batch file to set up location of fpc.exe
        exit /b 1
)
echo "%fpcexe%"
 
echo Building...
copy "..\..\dll\x86_64\libwebview.a" .
copy "..\..\dll\x86_64\webview.dll" .
copy "..\..\dll\x86_64\WebView2Loader.dll" .
"%fpcexe%" -Fu..\..\src -Fl. browser_cli.lpr
`

I think the dll and import library are 64bit while my fpc installation is 32 bit.
Could you put also the x32 dll please.

**Comment by PierceNg** [comment]
I've added i386 versions of webview.dll and WebView2Loader.dll to the repo. All demos tested working.
