### ISSUE TITLE
Suggestions for modifying the winbuild.bat file

### ISSUE THREAD

**Issue by delphius** [PierceNg/fpwebview#7]
Taking into account the fact that the assembly provides for compilation only for 64 bits, it is advisable to add -Twin64 -Px86_64 to the compilation options.
As for the paths to the compiler, on Windows, when installing fpc or lazarus, the PATH environment variable is automatically set, so in most cases, you can not specify the full path.
However, if for some reason PATH is not specified (or fpc is not installed at all), then in this case it is advisable to handle the error using errorlevel and give instructions for manually writing the full path to the compiler.

@echo off
echo Building...
copy "..\..\dll\x86_64\libwebview.a" .
copy "..\..\dll\x86_64\webview.dll" .
copy "..\..\dll\x86_64\WebView2Loader.dll" .
fpc.exe **-Twin64 -Px86_64** -Fu..\..\src -Fl. servcli.lpr
**if errorlevel 1 (
	echo ERROR: not found fpc.exe
	echo ERROR: Edit this batch file to set up location of fpc.exe
)**

**Comment by PierceNg** [comment]
Thanks. I've made the changes in ```feb2023```, the current development branch. Once the macOS updates are done I will merge that branch into ```master```.

**Comment by delphius** [comment]
Thanks. Have you not watched a similar promising project [Webui](https://github.com/webui-dev/webui) ?
