### ISSUE TITLE
Couple issues related to windows compilation

### ISSUE THREAD

**Issue by isighless** [PierceNg/fpwebview#8]
I am attaching a patch file for a couple of issues I ran into when I was trying to build your project on windows:

[fpwebview-58daefe-cc5b90c.patch](https://github.com/PierceNg/fpwebview/files/10865114/fpwebview-58daefe-cc5b90c.patch)

The only one I actually tested with was the browser_cli compilation, so you may want to make sure the change from libwebview to libimpwebview also makes sense the other places I did it..

**Comment by PierceNg** [comment]
Thanks. I've made the changes in ```feb2023```, the current development branch. Once the macOS updates are done I will merge that branch into ```master```.
